apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: mlflow
  name: mlflow-user-binding
subjects:
- kind: User
  name: user@example.com
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: mlflow-access
  apiGroup: rbac.authorization.k8s.io
