apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "irish-s3"
spec:
  predictor:
    serviceAccountName: sa
    model:
      modelFormat:
        name: mlflow
      protocolVersion: v2
      storageUri: "s3://mlflow/1/0a16c81425b741359e21f30d9894c6b6/artifacts/iris_model/"